let books = [
  {
    id: 1,
    title: "في غيبوبة",
    author: "أحمد خالد توفيق",
    stars: 5,
    downloads: 350,
  },
  {
    id: 2,
    title: "ذاكرة الجسد",
    author: "أحلام مستغانمي",
    stars: 5,
    downloads: 450,
  },
  {
    id: 3,
    title: "العمى",
    author: "جوزيه ساراماغو",
    stars: 5,
    downloads: 300,
  },
  {
    id: 4,
    title: "في قلبي أنثى عبرية",
    author: "أمل دنقل",
    stars: 5,
    downloads: 400,
  },
  {
    id: 5,
    title: "موسم الهجرة إلى الشمال",
    author: "طه حسين",
    stars: 5,
    downloads: 250,
  },
  {
    id: 6,
    title: "المرايا",
    author: "سوزان سونتاج",
    stars: 5,
    downloads: 420,
  },
  {
    id: 7,
    title: "الأصل",
    author: "خالد الخميسي",
    stars: 5,
    downloads: 280,
  },
  {
    id: 8,
    title: "ساق البامبو",
    author: "سعدي يوسف",
    stars: 5,
    downloads: 380,
  },
  {
    id: 9,
    title: "العائدون",
    author: "محمد حسن علوان",
    stars: 5,
    downloads: 290,
  },
  {
    id: 10,
    title: "أولاد حارتنا",
    author: "نجيب محفوظ",
    stars: 5,
    downloads: 460,
  },
  {
    id: 11,
    title: "بين القصرين",
    author: "نزار قباني",
    stars: 5,
    downloads: 400,
  },
  {
    id: 12,
    title: "الأرض والدم",
    author: "زكريا تامر",
    stars: 5,
    downloads: 270,
  },
  {
    id: 13,
    title: "باب الشمس",
    author: "توفيق الحكيم",
    stars: 5,
    downloads: 390,
  },
  {
    id: 14,
    title: "الرجال من المريخ، النساء من الزهرة",
    author: "جون غراي",
    stars: 5,
    downloads: 350,
  },
  {
    id: 15,
    title: "الفيل الأزرق",
    author: "أحمد مراد",
    stars: 5,
    downloads: 420,
  },
  {
    id: 16,
    title: "أولاد الغيتو",
    author: "إسماعيل الفاروقي",
    stars: 5,
    downloads: 300,
  },
  {
    id: 17,
    title: "الصفحة الثامنة",
    author: "غسان كنفاني",
    stars: 5,
    downloads: 470,
  },
  {
    id: 18,
    title: "الأبواب الموصدة",
    author: "مصطفى صادق الرافعي",
    stars: 5,
    downloads: 320,
  },
  {
    id: 19,
    title: "الفيلم الأمريكي",
    author: "محمد عبد النبي",
    stars: 5,
    downloads: 380,
  },
  {
    id: 20,
    title: "الطريق",
    author: "كورماك مكارثي",
    stars: 5,
    downloads: 250,
  },
  {
    id: 21,
    title: "الأسود يليق بك",
    author: "أحمد خالد توفيق",
    stars: 5,
    downloads: 400,
  },
  {
    id: 22,
    title: "عزازيل",
    author: "يوسف زيدان",
    stars: 5,
    downloads: 350,
  },
  {
    id: 23,
    title: "الخبز الحافي",
    author: "محمد شكري",
    stars: 5,
    downloads: 250,
  },
  {
    id: 24,
    title: "الدراويش",
    author: "نجيب محفوظ",
    stars: 5,
    downloads: 300,
  },
  {
    id: 25,
    title: "الأيام",
    author: "طه حسين",
    stars: 5,
    downloads: 450,
  },
  {
    id: 26,
    title: "لوداك",
    author: "غسان كنفاني",
    stars: 5,
    downloads: 420,
  },
  {
    id: 27,
    title: "موت في الأزهرية",
    author: "نجيب محفوظ",
    stars: 5,
    downloads: 480,
  },
  {
    id: 28,
    title: "تراب الماس",
    author: "أحمد مراد",
    stars: 5,
    downloads: 280,
  },
  {
    id: 29,
    title: "المواطن والمؤسسة والدولة",
    author: "عبد الله الطيب",
    stars: 5,
    downloads: 200,
  },
  {
    id: 30,
    title: "جريمة في المعادي",
    author: "أحمد مراد",
    stars: 5,
    downloads: 390,
  },
  {
    id: 31,
    title: "المغني",
    author: "عباس محمود العقاد",
    stars: 5,
    downloads: 330,
  },
  {
    id: 32,
    title: "الوجيز في الفقه الإسلامي",
    author: "صالح الفوزان",
    stars: 5,
    downloads: 250,
  },
  {
    id: 33,
    title: "الطريق إلى القدرة الذاتية",
    author: "نابليون هيل",
    stars: 5,
    downloads: 280,
  },
  {
    id: 34,
    title: "العرب والغرب",
    author: "إدوارد سعيد",
    stars: 5,
    downloads: 420,
  },
  {
    id: 35,
    title: "العمى الألوان",
    author: "محمد عبد الحافظ",
    stars: 5,
    downloads: 380,
  },
  {
    id: 36,
    title: "أعمدة الثقافة",
    author: "عبد الوهاب المسيري",
    stars: 5,
    downloads: 300,
  },
  {
    id: 37,
    title: "الرحلة إلى الطائف",
    author: "علي الوردي",
    stars: 5,
    downloads: 470,
  },
  {
    id: 38,
    title: "أهل الكهف",
    author: "عمرو الجندي",
    stars: 5,
    downloads: 350,
  },
  {
    id: 39,
    title: "البؤساء",
    author: "فيكتور هوجو",
    stars: 5,
    downloads: 450,
  },
  {
    id: 40,
    title: "الخيميائي",
    author: "بولو كويلو",
    stars: 5,
    downloads: 500,
  },
  {
    id: 41,
    title: "العصفور",
    author: "صلاح عبد الصبور",
    stars: 5,
    downloads: 250,
  },
  {
    id: 42,
    title: "المرأة النازفة",
    author: "أحمد خالد توفيق",
    stars: 5,
    downloads: 300,
  },
  {
    id: 43,
    title: "اليوم الذي توقف فيه الزمن",
    author: "أحمد خالد توفيق",
    stars: 5,
    downloads: 350,
  },
  {
    id: 44,
    title: "البؤساء",
    author: "فيكتور هوجو",
    stars: 5,
    downloads: 400,
  },
  {
    id: 45,
    title: "الرحلة الأخيرة",
    author: "نجيب محفوظ",
    stars: 5,
    downloads: 450,
  },
  {
    id: 46,
    title: "العمى",
    author: "جوزيه ساراماغو",
    stars: 5,
    downloads: 500,
  },
  {
    id: 47,
    title: "المصنع",
    author: "علاء الأسواني",
    stars: 5,
    downloads: 250,
  },
  {
    id: 48,
    title: "المرأة التي رسمت ظلها",
    author: "غسان كنفاني",
    stars: 5,
    downloads: 300,
  },
  {
    id: 49,
    title: "الأبواب المغلقة",
    author: "معروف الرصافي",
    stars: 5,
    downloads: 350,
  },
  {
    id: 50,
    title: "العزيف",
    author: "محمد المنسي قنديل",
    stars: 5,
    downloads: 400,
  },
  {
    id: 51,
    title: "التنين",
    author: "محمد نجيب الجمل",
    stars: 5,
    downloads: 450,
  },
  {
    id: 52,
    title: "العرب والفرس",
    author: "محمد حسنين هيكل",
    stars: 5,
    downloads: 500,
  },
  {
    id: 53,
    title: "النحاس في الهواء",
    author: "نجيب محفوظ",
    stars: 5,
    downloads: 250,
  },
  {
    id: 54,
    title: "الحرب والسلام",
    author: "ليو تولستوي",
    stars: 5,
    downloads: 300,
  },
  {
    id: 55,
    title: "القرآن الكريم",
    author: "الله",
    stars: 5,
    downloads: 350,
  },
  {
    id: 56,
    title: "الكون",
    author: "ستيفن هوكينج",
    stars: 5,
    downloads: 400,
  },
  {
    id: 57,
    title: "التجربة الألمانية",
    author: "طه حسين",
    stars: 5,
    downloads: 450,
  },
  {
    id: 58,
    title: "المائة ألف بستان",
    author: "نجيب محفوظ",
    stars: 5,
    downloads: 500,
  },
  {
    id: 59,
    title: "العائدون من الجحيم",
    author: "أحمد خالد توفيق",
    stars: 5,
    downloads: 250,
  },
  {
    id: 60,
    title: "المعلمون",
    author: "نجيب محفوظ",
    stars: 5,
    downloads: 300,
  },
  {
    id: 61,
    title: "الحرافيش",
    author: "نجيب محفوظ",
    stars: 5,
    downloads: 350,
  },
  {
    id: 62,
    title: "الأسود يليق بك",
    author: "أحمد خالد توفيق",
    stars: 5,
    downloads: 400,
  },
  {
    id: 63,
    title: "الطريق إلى القرية البعيدة",
    author: "نجيب محفوظ",
    stars: 5,
    downloads: 450,
  },
  {
    id: 64,
    title: "الشيطان يعبد الله",
    author: "عمرو عبد الحميد",
    stars: 5,
    downloads: 500,
  },
  {
    id: 65,
    title: "الخيميائي",
    author: "بولو كويلو",
    stars: 5,
    downloads: 250,
  },
  {
    id: 66,
    title: "عصر الظلام",
    author: "إحسان عبد القدوس",
    stars: 5,
    downloads: 300,
  },
  {
    id: 67,
    title: "الطريق إلى الإسلام",
    author: "محمد عبده",
    stars: 5,
    downloads: 350,
  },
  {
    id: 68,
    title: "الخان الأحمر",
    author: "يوسف السباعي",
    stars: 5,
    downloads: 400,
  },
  {
    id: 69,
    title: "العنكبوت",
    author: "إحسان عبد القدوس",
    stars: 5,
    downloads: 450,
  },
  {
    id: 70,
    title: "الأعمال الكاملة لشكسبير",
    author: "ويليام شكسبير",
    stars: 5,
    downloads: 500,
  },
  {
    id: 71,
    title: "مرحبا بك في العالم",
    author: "ChatGPT",
    stars: 5,
    downloads: 1000,
  },
  {
    id: 72,
    title: "ساعة صفر",
    author: "أحمد خالد توفيق",
    stars: 5,
    downloads: 800,
  },
  {
    id: 73,
    title: "الأسود يليق بك 2",
    author: "أحمد خالد توفيق",
    stars: 5,
    downloads: 900,
  },
  {
    id: 74,
    title: "الأسود يليق بك 3",
    author: "أحمد خالد توفيق",
    stars: 5,
    downloads: 700,
  },
  {
    id: 75,
    title: "الأمير",
    author: "مكياڤيلي",
    stars: 5,
    downloads: 600,
  },
  {
    id: 76,
    title: "الجزيرة",
    author: "عمرو عبد الحميد",
    stars: 5,
    downloads: 550,
  },
  {
    id: 77,
    title: "الشمس المشرقة",
    author: "يوكيو ميشيما",
    stars: 5,
    downloads: 400,
  },
  {
    id: 78,
    title: "حين يسكت الحب",
    author: "نزار قباني",
    stars: 5,
    downloads: 350,
  },
  {
    id: 79,
    title: "السيد أحمد عرابي",
    author: "محمد المنسي قنديل",
    stars: 5,
    downloads: 300,
  },
  {
    id: 80,
    title: "العروسة الثانية",
    author: "علاء الأسواني",
    stars: 5,
    downloads: 250,
  },
  {
    id: 81,
    title: "المرأة القرد",
    author: "د. نبيل فاروق",
    stars: 5,
    downloads: 450,
  },
  {
    id: 82,
    title: "الفيل الأزرق",
    author: "أحمد مراد",
    stars: 5,
    downloads: 800,
  },
  {
    id: 83,
    title: "الأسود يليق بك 4",
    author: "أحمد خالد توفيق",
    stars: 5,
    downloads: 900,
  },
  {
    id: 84,
    title: "الأسود يليق بك 5",
    author: "أحمد خالد توفيق",
    stars: 5,
    downloads: 700,
  },
  {
    id: 85,
    title: "الديوان",
    author: "أحمد شوقي",
    stars: 5,
    downloads: 600,
  },
  {
    id: 86,
    title: "الملك لير",
    author: "ويليام شكسبير",
    stars: 5,
    downloads: 550,
  },
  {
    id: 87,
    title: "أهلا بكم في الجحيم",
    author: "أحمد خالد توفيق",
    stars: 5,
    downloads: 400,
  },
  {
    id: 88,
    title: "البؤساء",
    author: "فيكتور هوجو",
    stars: 5,
    downloads: 350,
  },
  {
    id: 89,
    title: "الخيميائي",
    author: "بولو كويلو",
    stars: 5,
    downloads: 300,
  },
  {
    id: 90,
    title: "الأمير الصغير",
    author: "أنطوان دو سانت إكزوبيري",
    stars: 5,
    downloads: 250,
  },
  {
    id: 91,
    title: "المبدع",
    author: "ميخائيل نعيمة",
    stars: 5,
    downloads: 450,
  },
  {
    id: 92,
    title: "النمر الأسود",
    author: "إدجار رايس بوروز",
    stars: 5,
    downloads: 800,
  },
  {
    id: 93,
    title: "الأسود يليق بك 6",
    author: "أحمد خالد توفيق",
    stars: 5,
    downloads: 900,
  },
  {
    id: 94,
    title: "الأسود يليق بك 7",
    author: "أحمد خالد توفيق",
    stars: 5,
    downloads: 700,
  },
  {
    id: 95,
    title: "رجال في الشمس",
    author: "غسان كنفاني",
    stars: 5,
    downloads: 600,
  },
  {
    id: 96,
    title: "عيون القلب",
    author: "غسان كنفاني",
    stars: 5,
    downloads: 550,
  },
  {
    id: 97,
    title: "المصباح السحري",
    author: "محمد الغزالي",
    stars: 5,
    downloads: 400,
  },
  {
    id: 98,
    title: "حوار في الزمن",
    author: "نجيب محفوظ",
    stars: 5,
    downloads: 350,
  },
  {
    id: 99,
    title: "القرآن الكريم",
    author: "الله",
    stars: 5,
    downloads: 300,
  },
  {
    id: 100,
    title: "الأسود يليق بك 8",
    author: "أحمد خالد توفيق",
    stars: 5,
    downloads: 250,
  },
  {
    id: 101,
    title: "موت على النيل",
    author: "أغاثا كريستي",
    stars: 4.5,
    downloads: 1200,
  },
  {
    id: 102,
    title: "المليونير المتشرد",
    author: "مارك توين",
    stars: 4.2,
    downloads: 900,
  },
  {
    id: 103,
    title: "العهد القديم",
    author: "مجهول",
    stars: 4.7,
    downloads: 1500,
  },
  {
    id: 104,
    title: "العهد الجديد",
    author: "مجهول",
    stars: 4.8,
    downloads: 1600,
  },
  {
    id: 105,
    title: "الأفعى",
    author: "ألبرت كامو",
    stars: 4.1,
    downloads: 700,
  },
  {
    id: 106,
    title: "العالم الجوراسي",
    author: "مايكل كرايتون",
    stars: 4.6,
    downloads: 1100,
  },
  {
    id: 107,
    title: "حكاية الحرية",
    author: "مالكوم إكس",
    stars: 4.9,
    downloads: 1400,
  },
  {
    id: 108,
    title: "القوقعة",
    author: "عبدالرحمن منيف",
    stars: 4.3,
    downloads: 800,
  },
  {
    id: 109,
    title: "الرحيق المختوم",
    author: "صفي الرحمن المباركفوري",
    stars: 4.7,
    downloads: 1300,
  },
  {
    id: 110,
    title: "الفارس الأسود",
    author: "نجيب محفوظ",
    stars: 4.2,
    downloads: 750,
  },
  {
    id: 111,
    title: "الشيخ والمحبوبة",
    author: "جبران خليل جبران",
    stars: 4.6,
    downloads: 1000,
  },
  {
    id: 112,
    title: "العالم كما أراه",
    author: "ألبرت أينشتاين",
    stars: 4.9,
    downloads: 1700,
  },
  {
    id: 113,
    title: "التراث الفلسطيني",
    author: "أحمد الشقيري",
    stars: 4.3,
    downloads: 900,
  },
  {
    id: 114,
    title: "حكايات من الصحراء",
    author: "غسان كنفاني",
    stars: 4.7,
    downloads: 1200,
  },
  {
    id: 115,
    title: "الليل والنهار",
    author: "فريدريك نيتشه",
    stars: 4.1,
    downloads: 600,
  },
  {
    id: 116,
    title: "أنا ذاهب إلى السوق",
    author: "أحمد خالد توفيق",
    stars: 4.5,
    downloads: 950,
  },
  {
    id: 117,
    title: "الذئب والعصافير",
    author: "جبران خليل جبران",
    stars: 4.8,
    downloads: 1300,
  },
  {
    id: 118,
    title: "الستراتيجية العسكرية",
    author: "سن تزو",
    stars: 4.4,
    downloads: 1100,
  },
  {
    id: 119,
    title: "اليوم الأخير لحياتي",
    author: "محمد حسن علوان",
    stars: 4.2,
    downloads: 800,
  },
  {
    id: 120,
    title: "الهروب إلى الحرية",
    author: "إريك فروم",
    stars: 4.9,
    downloads: 1400,
  },
  {
    id: 121,
    title: "القبطان في الجيش",
    author: "فرانز كافكا",
    stars: 4.3,
    downloads: 700,
  },
  {
    id: 122,
    title: "العبقريات العشر",
    author: "جيمس واتسون",
    stars: 4.7,
    downloads: 1200,
  },
  {
    id: 123,
    title: "رسائل في الهواء",
    author: "رفعت السعيد",
    stars: 4.1,
    downloads: 750,
  },
  {
    id: 124,
    title: "السيدة بوفري",
    author: "غوستاف فلوبير",
    stars: 4.5,
    downloads: 900,
  },
  {
    id: 125,
    title: "الأمير",
    author: "نيكولو مكيافيلي",
    stars: 4.8,
    downloads: 1500,
  },
  {
    id: 126,
    title: "المسافر",
    author: "كنوت هامسون",
    stars: 4.4,
    downloads: 1100,
  },
  {
    id: 127,
    title: "حبيبتي الكتاب",
    author: "بيير لويس",
    stars: 4.2,
    downloads: 800,
  },
  {
    id: 128,
    title: "الخوف والترهيب في الأسلام",
    author: "عبد الوهاب المسيري",
    stars: 4.9,
    downloads: 1400,
  },
  {
    id: 129,
    title: "الرجل الذي كان يعيش في الحفرة",
    author: "جان بول سارتر",
    stars: 4.3,
    downloads: 700,
  },
  {
    id: 130,
    title: "المرأة الجميلة",
    author: "غادة عبد العال",
    stars: 4,
    downloads: 150,
  },
  {
    id: 131,
    title: "القط الأسود",
    author: "أحمد مراد",
    stars: 4.5,
    downloads: 300,
  },
  {
    id: 132,
    title: "المخبر الشريف",
    author: "صالح مرسي",
    stars: 3.5,
    downloads: 200,
  },
  {
    id: 133,
    title: "ملائكة وشياطين",
    author: "دان براون",
    stars: 4,
    downloads: 350,
  },
  {
    id: 134,
    title: "الرجل الذي لم يكن ليكون",
    author: "أحمد خالد توفيق",
    stars: 4.5,
    downloads: 400,
  },
  {
    id: 135,
    title: "ليالي أوجيني",
    author: "أحمد خالد توفيق",
    stars: 4,
    downloads: 450,
  },
  {
    id: 136,
    title: "الطائر المبكر",
    author: "محمد صادق",
    stars: 3.5,
    downloads: 250,
  },
  {
    id: 137,
    title: "حكاية الحب",
    author: "جين أوستن",
    stars: 5,
    downloads: 500,
  },
  {
    id: 138,
    title: "الضوء الذي لا ينطفئ",
    author: "أحمد خالد توفيق",
    stars: 4.5,
    downloads: 550,
  },
  {
    id: 139,
    title: "بيت العنكبوت",
    author: "إبراهيم عبد المجيد",
    stars: 4,
    downloads: 600,
  },
  {
    id: 140,
    title: "الفيل الأزرق",
    author: "أحمد مراد",
    stars: 4.5,
    downloads: 650,
  },
  {
    id: 141,
    title: "كوخ العمدة",
    author: "نجيب محفوظ",
    stars: 3.5,
    downloads: 700,
  },
  {
    id: 142,
    title: "الجوهر المسروق",
    author: "أغاثا كريستي",
    stars: 4,
    downloads: 750,
  },
  {
    id: 143,
    title: "عودة الروح",
    author: "أحمد خالد توفيق",
    stars: 4.5,
    downloads: 800,
  },
  {
    id: 144,
    title: "أرض الجمال",
    author: "جبران خليل جبران",
    stars: 4,
    downloads: 850,
  },
  {
    id: 145,
    title: "النهاية",
    author: "ميشيل هويلبيك",
    stars: 3.5,
    downloads: 900,
  },
  {
    id: 146,
    title: "سوف تراه عيناي",
    author: "أحمد خالد توفيق",
    stars: 4.5,
    downloads: 950,
  },
  {
    id: 147,
    title: "الذئب",
    author: "جاك لندن",
    stars: 4,
    downloads: 1000,
  },
  {
    id: 148,
    title: "المتاهة",
    author: "جيمس داشنر",
    stars: 4.5,
    downloads: 1050,
  },
  {
    id: 149,
    title: "الشيخوخة",
    author: "نجيب محفوظ",
    stars: 3.5,
    downloads: 1100,
  },
  {
    id: 150,
    title: "طريق الحرير",
    author: "إبراهيم عبد المجيد",
    stars: 4,
    downloads: 1150,
  },
  {
    id: 151,
    title: "مذكرات امرأة شابة",
    author: "سيمون دو بوفوار",
    stars: 4.5,
    downloads: 1200,
  },
  {
    id: 152,
    title: "العهد القديم",
    author: "أحمد خالد توفيق",
    stars: 4,
    downloads: 1250,
  },
  {
    id: 153,
    title: "دائرة الضوء",
    author: "أحمد خالد توفيق",
    stars: 4.5,
    downloads: 1300,
  },
  {
    id: 154,
    title: "تراب الماس",
    author: "أحمد مراد",
    stars: 4,
    downloads: 1350,
  },
  {
    id: 155,
    title: "الجنائزي",
    author: "فتحي الضو",
    stars: 4.5,
    downloads: 1400,
  },
  {
    id: 156,
    title: "البؤساء",
    author: "فيكتور هوجو",
    stars: 5,
    downloads: 1450,
  },
  {
    id: 157,
    title: "الكونت مونتي كريستو",
    author: "ألكسندر دوما",
    stars: 4.5,
    downloads: 1500,
  },
  {
    id: 158,
    title: "فرانكشتاين",
    author: "ماري شيلي",
    stars: 4,
    downloads: 1550,
  },
  {
    id: 159,
    title: "الحب في زمن الكوليرا",
    author: "جابرييل غارسيا ماركيز",
    stars: 4.5,
    downloads: 1600,
  },
  {
    id: 160,
    title: "البئر والتوت",
    author: "نجيب محفوظ",
    stars: 3.5,
    downloads: 1650,
  },
  {
    id: 161,
    title: "رجال في الشمس",
    author: "غسان كنفاني",
    stars: 4.5,
    downloads: 1700,
  },
  {
    id: 162,
    title: "الأمير",
    author: "نيكولو مكيافيلي",
    stars: 4,
    downloads: 1750,
  },
  {
    id: 163,
    title: "أحلام الفتى الطائر",
    author: "جبران خليل جبران",
    stars: 4.5,
    downloads: 1800,
  },
  {
    id: 164,
    title: "الساحر",
    author: "جون فو",
    stars: 4,
    downloads: 1850,
  },
  {
    id: 165,
    title: "ألف ليلة وليلة",
    author: "غير معروف",
    stars: 4.5,
    downloads: 1900,
  },
  {
    id: 166,
    title: "موسم الهجرة إلى الشمال",
    author: "توفيق الحكيم",
    stars: 4,
    downloads: 1950,
  },
  {
    id: 167,
    title: "الأصليون",
    author: "توفيق الحكيم",
    stars: 4.5,
    downloads: 2000,
  },
  {
    id: 168,
    title: "الطريق",
    author: "جاك كراكور",
    stars: 4,
    downloads: 2050,
  },
  {
    id: 169,
    title: "محطة النيل",
    author: "محمد صادق",
    stars: 4.5,
    downloads: 2100,
  },
  {
    id: 170,
    title: "العائلة كريمة",
    author: "نجيب محفوظ",
    stars: 3.5,
    downloads: 2150,
  },
  {
    id: 171,
    title: "جبنة البارميزان",
    author: "أحمد مراد",
    stars: 4.5,
    downloads: 2200,
  },
  {
    id: 172,
    title: "العمى",
    author: "جوزيه ساراماجو",
    stars: 4,
    downloads: 2250,
  },
  {
    id: 173,
    title: "الحكاية الخضراء",
    author: "ماريو فارجاس لوسا",
    stars: 4.5,
    downloads: 2300,
  },
  {
    id: 174,
    title: "الميت السعيد",
    author: "ألبرت كامو",
    stars: 4,
    downloads: 2350,
  },
  {
    id: 175,
    title: "أوراق من الربيع",
    author: "تشارلز ديكنز",
    stars: 4.5,
    downloads: 2400,
  },
  {
    id: 176,
    title: "حكايات من البخاري",
    author: "غير معروف",
    stars: 4,
    downloads: 2450,
  },
  {
    id: 177,
    title: "الخيميائي",
    author: "بولو كويلو",
    stars: 4.5,
    downloads: 2500,
  },
  {
    id: 178,
    title: "دفاتر موسى",
    author: "مصطفى صادق الرافعي",
    stars: 4,
    downloads: 2550,
  },
  {
    id: 179,
    title: "أنتيخريستوس",
    author: "نجيب محفوظ",
    stars: 4.5,
    downloads: 2600,
  },
  {
    id: 180,
    title: "زنزانة الفردوس",
    author: "أحمد خالد توفيق",
    stars: 3.5,
    downloads: 2650,
  },
  {
    id: 181,
    title: "المنطقة المحرمة",
    author: "محمد عبد الحليم عبد الله",
    stars: 4.5,
    downloads: 2700,
  },
  {
    id: 182,
    title: "مدينة الشمس",
    author: "د. عائض القرني",
    stars: 4,
    downloads: 270,
  },
  {
    id: 183,
    title: "رحلة إلى الأبدية",
    author: "د. عائض القرني",
    stars: 4.5,
    downloads: 280,
  },
  {
    id: 184,
    title: "السر العظيم",
    author: "روندا بايرن",
    stars: 4,
    downloads: 290,
  },
  {
    id: 185,
    title: "في ظلال القرآن",
    author: "سيد قطب",
    stars: 4.5,
    downloads: 300,
  },
  {
    id: 186,
    title: "الرحيق المختوم",
    author: "صفي الرحمن المباركفوري",
    stars: 4,
    downloads: 310,
  },
  {
    id: 187,
    title: "الخطاب الديني في الإسلام",
    author: "سيد قطب",
    stars: 4.5,
    downloads: 320,
  },
  {
    id: 188,
    title: "الدليل الكامل للصيانة والإصلاح",
    author: "كريسوفر شوارتز",
    stars: 4,
    downloads: 330,
  },
  {
    id: 189,
    title: "الفن التجريدي",
    author: "فهد الشمري",
    stars: 4.5,
    downloads: 340,
  },
  {
    id: 190,
    title: "الكفاح الفلسطيني",
    author: "إدوارد سعيد",
    stars: 4,
    downloads: 350,
  },
  {
    id: 191,
    title: "المقدمة الشاملة في علم النفس",
    author: "ويليام جيمس",
    stars: 4.5,
    downloads: 360,
  },
  {
    id: 192,
    title: "الفلسفة الأخلاقية",
    author: "أريستوتيليس",
    stars: 4,
    downloads: 370,
  },
  {
    id: 193,
    title: "أصول الفقه الإسلامي",
    author: "محمد الطاهر بن عاشور",
    stars: 4.5,
    downloads: 380,
  },
  {
    id: 194,
    title: "المسيحية والإسلام",
    author: "جيمس وينستون موريس",
    stars: 4,
    downloads: 390,
  },
  {
    id: 195,
    title: "التحكم الذاتي",
    author: "ديل كارنيجي",
    stars: 4.5,
    downloads: 400,
  },
  {
    id: 196,
    title: "الحياة في القرن الحادي والعشرين",
    author: "جيرالد دوركين",
    stars: 4,
    downloads: 410,
  },
  {
    id: 197,
    title: "التأملات في الإيمان",
    author: "بابا بندكت السادس عشر",
    stars: 4.5,
    downloads: 420,
  },
  {
    id: 198,
    title: "العلاقات العامة والإعلام",
    author: "جون ديفيدز",
    stars: 4,
    downloads: 430,
  },
  {
    id: 199,
    title: "الهندسة الكهربائية",
    author: "محمد الرخاوي",
    stars: 4.5,
    downloads: 440,
  },
  {
    id: 200,
    title: "الهندسة المدنية",
    author: "محمد الرخاوي",
    stars: 4,
    downloads: 450,
  },
  {
    id: 201,
    title: "رجل غير عادي",
    author: "باتريك أوين",
    stars: 4.5,
    downloads: 460,
  },
  {
    id: 202,
    title: "النسوية والأدب",
    author: "سلوى النحاس",
    stars: 4,
    downloads: 470,
  },
  {
    id: 203,
    title: "المعالجة النفسية للأطفال المعاقين",
    author: "ماري بارتون",
    stars: 4.5,
    downloads: 480,
  },
  {
    id: 204,
    title: "التعليم الإلكتروني",
    author: "محمد مقبول",
    stars: 4,
    downloads: 490,
  },
  {
    id: 205,
    title: "المعلم الفاشل",
    author: "صلاح الدين العجمي",
    stars: 4.5,
    downloads: 500,
  },
  {
    id: 206,
    title: "التغيير الاجتماعي",
    author: "أوليفر كرومويل",
    stars: 4,
    downloads: 510,
  },
  {
    id: 207,
    title: "تاريخ الحضارة الإسلامية",
    author: "عبدالرحمن بديوي",
    stars: 4.5,
    downloads: 520,
  },
  {
    id: 208,
    title: "الفلسفة السياسية",
    author: "أرسطو",
    stars: 4,
    downloads: 530,
  },
  {
    id: 209,
    title: "التحولات الاقتصادية والاجتماعية في العصر الحديث",
    author: "كارل ماركس",
    stars: 4.5,
    downloads: 540,
  },
  {
    id: 210,
    title: "العالم بعيون رواد الفضاء",
    author: "نيل ديغراس تايسون",
    stars: 4,
    downloads: 550,
  },
  {
    id: 211,
    title: "الفن في الثقافة الإسلامية",
    author: "وائل فتحي",
    stars: 4.5,
    downloads: 560,
  },
  {
    id: 212,
    title: "التحولات الاجتماعية في المجتمع العربي",
    author: "عبد الله العروي",
    stars: 4,
    downloads: 570,
  },
  {
    id: 213,
    title: "الإنسان والبيئة",
    author: "جاريد دايموند",
    stars: 4.5,
    downloads: 580,
  },
  {
    id: 214,
    title: "التحرر النسائي في العالم العربي",
    author: "فاطمة المرنيسي",
    stars: 4,
    downloads: 590,
  },
  {
    id: 215,
    title: "العلماء والعرب",
    author: "يوسف زيدان",
    stars: 4.5,
    downloads: 600,
  },
  {
    id: 216,
    title: "الشعر العربي الحديث",
    author: "عبد الوهاب المسيري",
    stars: 4,
    downloads: 610,
  },
  {
    id: 217,
    title: "الفن التشكيلي العربي",
    author: "محمد خير الزين",
    stars: 4.5,
    downloads: 620,
  },
  {
    id: 218,
    title: "العولمة وتحولات القوى العالمية",
    author: "ميشيل فوكو",
    stars: 4,
    downloads: 630,
  },
  {
    id: 219,
    title: "التحولات الديموغرافية في العالم",
    author: "جون كينيث غالبريث",
    stars: 4.5,
    downloads: 640,
  },
  {
    id: 220,
    title: "التواصل الجديد",
    author: "محمد عبد العزيز الغريب",
    stars: 4,
    downloads: 650,
  },
  {
    id: 221,
    title: "المسرح العربي",
    author: "سامي خليل",
    stars: 4.5,
    downloads: 660,
  },
  {
    id: 222,
    title: "الفن السينمائي العربي",
    author: "أحمد شوقي",
    stars: 4,
    downloads: 670,
  },
  {
    id: 223,
    title: "الرياضة والصحة النفسية",
    author: "جوناثان فوكس",
    stars: 4.5,
    downloads: 680,
  },
  {
    id: 224,
    title: "التراث العربي",
    author: "عبد الله النفيسي",
    stars: 4,
    downloads: 690,
  },
  {
    id: 225,
    title: "التصميم الجرافيكي",
    author: "حسام الدين رضوان",
    stars: 4.5,
    downloads: 700,
  },
  {
    id: 226,
    title: "التصوير الضوئي",
    author: "جمال حمدان",
    stars: 4,
    downloads: 710,
  },
  {
    id: 227,
    title: "الصحافة المستقلة",
    author: "رحمة الله السعيد",
    stars: 4.5,
    downloads: 720,
  },
  {
    id: 228,
    title: "النظرية السياسية",
    author: "جون راونتري",
    stars: 4,
    downloads: 730,
  },
  {
    id: 229,
    title: "التسويق الرقمي",
    author: "رامي عزت",
    stars: 4.5,
    downloads: 740,
  },
  {
    id: 230,
    title: "التميز في الأعمال",
    author: "توم بيترز",
    stars: 4,
    downloads: 750,
  },
  {
    id: 231,
    title: "الأدب العربي الحديث",
    author: "عبد الرحمن منيف",
    stars: 4.5,
    downloads: 760,
  },
  {
    id: 232,
    title: "الإدارة العامة",
    author: "محمد عبد العزيز علي",
    stars: 4,
    downloads: 770,
  },
  {
    id: 233,
    title: "القيادة التحويلية",
    author: "جيمس ماكغريغور",
    stars: 4.5,
    downloads: 780,
  },
  {
    id: 234,
    title: "التنمية الاجتماعية",
    author: "ريتشارد تيتلر",
    stars: 4,
    downloads: 790,
  },
  {
    id: 235,
    title: "التعليم المفتوح",
    author: "محمد عبد الوهاب",
    stars: 4.5,
    downloads: 800,
  },
  {
    id: 236,
    title: "التعليم الإلكتروني",
    author: "محمد الجارحي",
    stars: 4,
    downloads: 810,
  },
  {
    id: 237,
    title: "التعليم العالي",
    author: "صفاء فتحي",
    stars: 4.5,
    downloads: 820,
  },
  {
    id: 238,
    title: "التكنولوجيا الحيوية",
    author: "أحمد الدويري",
    stars: 4,
    downloads: 830,
  },
  {
    id: 239,
    title: "الهندسة المدنية",
    author: "محمد ناجي",
    stars: 4.5,
    downloads: 840,
  },
  {
    id: 240,
    title: "العمارة الإسلامية",
    author: "محمد عطية",
    stars: 4,
    downloads: 850,
  },
  {
    id: 241,
    title: "الشعر العربي القديم",
    author: "أحمد شوقي",
    stars: 4.5,
    downloads: 860,
  },
  {
    id: 242,
    title: "الرسم الفني",
    author: "فرح عبد الرحمن",
    stars: 4,
    downloads: 870,
  },
  {
    id: 243,
    title: "الموسيقى العربية",
    author: "محمد عبد الوهاب",
    stars: 4.5,
    downloads: 880,
  },
  {
    id: 244,
    title: "التصميم الداخلي",
    author: "أحمد محمود",
    stars: 4,
    downloads: 890,
  },
  {
    id: 245,
    title: "التصميم الصناعي",
    author: "محمد السيد",
    stars: 4.5,
    downloads: 900,
  },
  {
    id: 246,
    title: "التصميم الجرافيكي المتقدم",
    author: "علي الخطيب",
    stars: 4,
    downloads: 910,
  },
  {
    id: 247,
    title: "التصوير الفوتوغرافي",
    author: "محمد حمدي",
    stars: 4.5,
    downloads: 920,
  },
  {
    id: 248,
    title: "الأفلام الوثائقية",
    author: "ياسر فاروق",
    stars: 4,
    downloads: 930,
  },
  {
    id: 249,
    title: "الأفلام الروائية",
    author: "أحمد خالد توفيق",
    stars: 4.5,
    downloads: 940,
  },
  {
    id: 250,
    title: "الأفلام الوثائقية السياسية",
    author: "عبد الحليم قنديل",
    stars: 4,
    downloads: 950,
  },
  {
    id: 251,
    title: "التصوير السينمائي",
    author: "محمد وائل",
    stars: 4.5,
    downloads: 960,
  },
  {
    id: 252,
    title: "التصوير السينمائي المتقدم",
    author: "عمرو السعيد",
    stars: 4,
    downloads: 970,
  },
  {
    id: 253,
    title: "الكتابة الإبداعية",
    author: "نجيب محفوظ",
    stars: 4.5,
    downloads: 980,
  },
  {
    id: 254,
    title: "النقد الأدبي",
    author: "حنان الشيخ",
    stars: 4,
    downloads: 990,
  },
  {
    id: 255,
    title: "الترجمة الأدبية",
    author: "صلاح فضل",
    stars: 4.5,
    downloads: 1000,
  },
  {
    id: 256,
    title: "الترجمة الفنية",
    author: "محمد نجيب",
    stars: 4,
    downloads: 1010,
  },
  {
    id: 257,
    title: "الفن التشكيلي",
    author: "عبد الرحمن النجدي",
    stars: 4.5,
    downloads: 1020,
  },
  {
    id: 258,
    title: "التمثيل",
    author: "نادية لطفي",
    stars: 4,
    downloads: 1030,
  },
  {
    id: 259,
    title: "الرقص الشرقي",
    author: "صابرين",
    stars: 4.5,
    downloads: 1040,
  },
  {
    id: 260,
    title: "الرقص الحديث",
    author: "آمال ماهر",
    stars: 4,
    downloads: 1050,
  },
  {
    id: 261,
    title: "الغناء العربي",
    author: "عبد الحليم حافظ",
    stars: 4.5,
    downloads: 1060,
  },
  {
    id: 262,
    title: "الأدب الإنجليزي",
    author: "شكسبير",
    stars: 4,
    downloads: 1070,
  },
  {
    id: 263,
    title: "الأدب الفرنسي",
    author: "فولتير",
    stars: 4.5,
    downloads: 1080,
  },
  {
    id: 264,
    title: "الأدب الألماني",
    author: "غوته",
    stars: 4,
    downloads: 1090,
  },
  {
    id: 265,
    title: "الأدب الإيطالي",
    author: "دانتي",
    stars: 4.5,
    downloads: 1100,
  },
  {
    id: 266,
    title: "الأدب الإسباني",
    author: "سيرفانتس",
    stars: 4,
    downloads: 1110,
  },
  {
    id: 267,
    title: "الأدب الروسي",
    author: "تولستوي",
    stars: 4.5,
    downloads: 1120,
  },
  {
    id: 268,
    title: "الأدب الأمريكي",
    author: "مارك توين",
    stars: 4,
    downloads: 1130,
  },
  {
    id: 269,
    title: "الأدب الصيني",
    author: "لي بو",
    stars: 4.5,
    downloads: 1140,
  },
  {
    id: 270,
    title: "الأدب الياباني",
    author: "موراكامي",
    stars: 4,
    downloads: 1150,
  },
  {
    id: 271,
    title: "الأدب الهندي",
    author: "رابندراناث طاغور",
    stars: 4.5,
    downloads: 1160,
  },
  {
    title: "الأدب العالمي",
    author: "أحمد مراد",
    stars: 4,
    downloads: 1170,
  },
];
let mainBooks = document.querySelector(".all-books");
let currentImageIndex = 0;

function showBooks() {
  let myMainBooks = books
    .map((book, index) => {
      currentImageIndex = (currentImageIndex % 40) + 1;
      return `
        <div class="book">
          <a class="book-img" href="bookposition.html" >
            <img src="assets/images/${currentImageIndex}.jpg" alt="${
        book.title
      }" loading="lazy" />
          </a>
          <a class="book-title" href="bookposition.html">  ${book.title}</a>
          <a class="book-author" href="authorBrief.html"> ${book.author}</a>
          <div class="stars-downloads-bookmark">
            <div class="stars">
                <i class="fa-solid fa-star active"></i>
                <i class="fa-solid fa-star active"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i> 
            </div>
            <p class="persons-rating">(<span>${Math.floor(
              Math.random() * book.downloads + 1
            )}</span>)</p>
            <i class="fa-solid fa-bookmark bookmark"></i>
          </div>
        </div>
      `;
    })
    .join("");
  mainBooks.innerHTML = myMainBooks;
}

showBooks();

// getting random rating to the books
let AllStars = document.querySelectorAll(".stars");
AllStars.forEach((stars) => {
  let ratingStars = stars.getElementsByClassName("fa-star");
  let ratingNumber = Math.floor(Math.random() * 5);
  if (ratingNumber === 0) {
    stars.nextElementSibling.querySelector(" span").textContent = "0";
  } else {
    for (let i = 0; i < ratingNumber; i++) {
      ratingStars[i].classList.add("active");
    }
  }
});
// the part of the reloading on the scroll
let booksToShow = 18;
let lastBooksShown = 18;
let allBooks = document.querySelector(".all-books").children.length;
// disappear all books
for (let i = 0; i < allBooks; i++) {
  document.querySelector(".all-books").children[i].style.display = "none";
}
//  show all books of your page
for (let i = 0; i < booksToShow; i++) {
  document.querySelector(`.book:nth-child(${i + 1})`).style.display = "block";
}
// making scroll on the books
window.addEventListener("scroll", () => {
  let scrollToTop = window.scrollY || document.documentElement.scrollTop;
  let windowHeight =
    window.innerHeight || document.documentElement.clientHeight;
  let documentHeight = document.documentElement.scrollHeight;
  if (scrollToTop + windowHeight === documentHeight) {
    var totalBooks;
    totalBooks = lastBooksShown + 18;
    if (totalBooks <= allBooks) {
      for (let i = lastBooksShown; i < totalBooks; i++) {
        setTimeout(() => {
          document.querySelector(".loader").classList.add("active-loader");
        }, 1);
        setTimeout(() => {
          document.querySelector(".loader").classList.remove("active-loader");
        }, 1500);
        setTimeout(() => {
          document.querySelector(`.book:nth-child(${i + 1})`).style.display =
            "block";
        }, 1600);
      }
      lastBooksShown = totalBooks;
    }
  }
});
